from backend.app.schemas.common import APIResponse, ErrorDetail
from backend.app.schemas.auth import (
    UserRegisterRequest,
    UserLoginRequest,
    UserResponse,
    TokenResponse,
    UserProfileUpdate,
)
from backend.app.schemas.document import (
    Party,
    DocumentSection,
    StructuredDocumentContent,
    DocumentCreateRequest,
    DocumentUpdateRequest,
    DocumentVersionResponse,
    DocumentResponse,
    DocumentListItem,
)
from backend.app.schemas.template import (
    TemplateField,
    TemplateSchema,
    TemplateCreateRequest,
    TemplateResponse,
)
from backend.app.schemas.ai import (
    GenerateDocumentRequest,
    ImproveClauseRequest,
    ImproveClauseResponse,
    ExplainClauseRequest,
    ExplainClauseResponse,
    SummarizeDocumentRequest,
    SummarizeDocumentResponse,
    DocumentAnalysisResponse,
    KeyClauseItem,
    RiskItem,
)
from backend.app.schemas.upload import UploadResponse

__all__ = [
    "APIResponse",
    "ErrorDetail",
    "UserRegisterRequest",
    "UserLoginRequest",
    "UserResponse",
    "TokenResponse",
    "UserProfileUpdate",
    "Party",
    "DocumentSection",
    "StructuredDocumentContent",
    "DocumentCreateRequest",
    "DocumentUpdateRequest",
    "DocumentVersionResponse",
    "DocumentResponse",
    "DocumentListItem",
    "TemplateField",
    "TemplateSchema",
    "TemplateCreateRequest",
    "TemplateResponse",
    "GenerateDocumentRequest",
    "ImproveClauseRequest",
    "ImproveClauseResponse",
    "ExplainClauseRequest",
    "ExplainClauseResponse",
    "SummarizeDocumentRequest",
    "SummarizeDocumentResponse",
    "DocumentAnalysisResponse",
    "KeyClauseItem",
    "RiskItem",
    "UploadResponse",
]
